# Generated by Django 6.0.5 on 2026-05-19 10:03

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField()),
                ('interest_rate_apy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('is_cancellable', models.BooleanField(default=True)),
                ('cancellation_penalty_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate_apy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_CANCELLATION', 'Pending Cancellation'), ('CANCELLED', 'Cancelled'), ('MATURED', 'Matured')], default='ACTIVE', max_length=30)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('mt5_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pending_upgrade_apy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='investments.investmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('clawback_interest_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_refund_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('refund_date', models.DateField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_cancellations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cancellations', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='investments.contract')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('request_payload', models.TextField()),
                ('response_payload', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('role', models.CharField(choices=[('INVESTOR', 'Investor'), ('MANAGER', 'Manager')], default='INVESTOR', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Wallet Deposit'), ('WITHDRAWAL', 'Wallet Withdrawal'), ('INVESTMENT', 'Investment Block (MT5)'), ('INTEREST_PAYOUT', 'Interest Payout'), ('REFUND', 'Principal Refund'), ('PENALTY', 'Early Cancellation Penalty'), ('CLAWBACK', 'Interest Clawback')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investments.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyInterestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_interest_logs', to='investments.contract')),
            ],
            options={
                'unique_together': {('contract', 'date')},
            },
        ),
    ]
